services:
  node_1:
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
      target: development
    ports:
      - 3000:3000
    environment:
      - NODE_ID=node_1
      - HOST=0.0.0.0
      - PORT=3000
      - BOOT_NODE=1
    volumes:
      - ./apps/node/:/usr/src/app
    healthcheck:
      test: ['CMD', 'curl', 'http://node_1:3000/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  node_2:
    depends_on:
      node_1:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
      target: development
    ports:
      - 3001:3000
    environment:
      - NODE_ID=node_2
      - HOST=0.0.0.0
      - PORT=3000
      - BOOT_NODE_ID=node_1
      - BOOT_NODE_HOST=0.0.0.0
      - BOOT_NODE_PORT=3000
    volumes:
      - ./apps/node/:/usr/src/app
