services:
  node-1:
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
      target: development
    ports:
      - 3000:3000
    environment:
      - NODE_ID=node-1
      - HOST=0.0.0.0
      - PORT=3000
      - BOOT_NODE=1
    volumes:
      - ./apps/node/:/usr/src/app
  node-2:
    depends_on:
      - node-1
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
      target: development
    ports:
      - 3001:3000
    environment:
      - NODE_ID=node-2
      - HOST=0.0.0.0
      - PORT=3000
      - BOOT_NODE_ID=node-1
      - BOOT_NODE_HOST=0.0.0.0
      - BOOT_NODE_PORT=3000
    volumes:
      - ./apps/node/:/usr/src/app
