services:
  node-1:
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
      target: development
      args:
        API_PORT: 3000
        API_HOST: '0.0.0.0'
    ports:
      - 3000:3000
    environment:
      - NODE_ID=node-1
      - FASTAPI_PORT=3000
      - BOOT_NODE=1
    volumes:
      - ./apps/node/:/usr/src/app
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://0.0.0.0:3000/health',
        ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
  node-2:
    depends_on:
      node-1:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./apps/node/Dockerfile
      target: development
      args:
        API_PORT: 3000
        API_HOST: '0.0.0.0'
    ports:
      - 3001:3000
    environment:
      - NODE_ID=node-2
      - FASTAPI_PORT=3000
      - BOOT_NODE_ID=node-1
      - BOOT_NODE_HOST=0.0.0.0
      - BOOT_NODE_PORT=3000
    volumes:
      - ./apps/node/:/usr/src/app
